picturama:
  album_source: '[your_path_here]'
  allowed_formats: ['jpg','png','jpeg','JPG']
  thumbnail_prefix: thumb_
  thumnail_default_size: "200x200"
  resized_prefix: resized_
  resized_default_size: "800x800"